api_platform:
    title: Hello API Platform
    version: 1.0.0
    formats:
        json: ['application/json']
        jsonld: ['application/ld+json']
    defaults:
        pagination_items_per_page: 100
        pagination_maximum_items_per_page: 100            
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
